### ISSUE TITLE
Use `merkle-tree` library instead

### ISSUE THREAD

**Issue by pcaversaccio** [0xngmi/zach-refund#2]
What's the reason for not using the well-maintained OZ library [`merkle-tree`](https://github.com/OpenZeppelin/merkle-tree)? I do understand that the common attack vectors are not an issue, but we should set an industry precedence here regarding what is best practice and I recommend using the OZ library.

PS: For anyone coming here and interested in the reason why we (generally) need double hashing, I added the explanation here https://github.com/OpenZeppelin/merkle-tree/commit/fc56e442d877ad6c616860faba5341da0d417d8b.

**Comment by 0xngmi** [comment]
only reason is that i based this code off my tubby cat code and i didn't use the oz library back then (not sure if merkle-tree library didnt exist back then or if i ran into some issue with it)

double hashing here doesnt seem necessary cause the attack you mentioned would require a preimage attack on the hash function, would this be correct?

**Comment by pcaversaccio** [comment]
> double hashing here doesnt seem necessary cause the attack you mentioned would require a preimage attack on the hash function, would this be correct?

Well, it would require that the leaf values be 64 bytes long _prior_ to hashing. Now, if I understood correctly you essentially abi encode (i.e. including padding) the `msg.sender` and `uint256` amount before `keccak256` hashing. Each of these parameters is encoded as 32 bytes and thus we get to 64 bytes overall. Or do I understand something wrong here about your approach?

**Comment by 0xngmi** [comment]
so lets say you take a middle node and pass it as a leaf node, the issue in that case is that the first child node of that middle node needs to be equal to msg.sender to pass verification, so attacker would need to pick a random hash and find the private key that generates an address that matches this hash, because he needs to send a tx from that address, is that correct? (furthermore the chances of the hash having the first 96 bits be all zeros is 2^-96, which is very low)

and if someone is able to perform this type of attack then ethereum would be rekt cause it relies on that not being possible

**Comment by pcaversaccio** [comment]
This is 100% correct yes. I just rechecked the contract code and saw that you use `msg.sender`, which is the best approach in this context. And yes, there are $2^{96}$ private keys for each Ethereum address (including the zero address). So $2^{96}$ chances to break it :). jk aside, so you feel safe going with `merkletreejs`? Has this library ever been audited actually? I mean, I know, it has been used many times, but I'm just paranoid when it comes to security.

**Comment by cygaar** [comment]
@pcaversaccio I assume you meant to type out 2^96 private keys per public address right? The markdown formatting is parsing your 2 ** 96 as bolded text lol.

**Comment by pcaversaccio** [comment]
> @pcaversaccio I assume you meant to type out 2^96 private keys per public address right? The markdown formatting is parsing your 2 ** 96 as bolded text lol.

Oooops :) - Now I even used the fancy LaTeX style lol

**Comment by pcaversaccio** [comment]
Closing this issue as not planned.
